In [24]:
import numpy as np
arr=[1 ,3 ,4]
matrice=np.array([arr,arr,arr])

In [25]:
print(matrice)

[[1 3 4]
 [1 3 4]
 [1 3 4]]


In [9]:
vecteur=np.arange(1,10,1)
print(vecteur)

[1 2 3 4 5 6 7 8 9]


In [26]:
eye=np.eye(3)
eye
print(np.linalg.inv(eye))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
lin=np.linspace(1,2,5)
lin
li=lin >1.2
li
lip=lin[lin >1]
lip

array([1.25, 1.5 , 1.75, 2.  ])

In [37]:
ran=np.random.random((3,3))
ran

array([[0.62550934, 0.28679224, 0.25993094],
       [0.52848772, 0.02909826, 0.07717804],
       [0.12825121, 0.31797532, 0.18702898]])

In [54]:
Bg=np.linspace(0,20,10)
B=np.where(Bg>2)
Bg=Bg[1:10]
Bg

array([ 2.22222222,  4.44444444,  6.66666667,  8.88888889, 11.11111111,
       13.33333333, 15.55555556, 17.77777778, 20.        ])

In [56]:
Bg=Bg.reshape(3,3)
Bg

array([[ 2.22222222,  4.44444444,  6.66666667],
       [ 8.88888889, 11.11111111, 13.33333333],
       [15.55555556, 17.77777778, 20.        ]])

In [57]:
Bg[0,-1]

6.666666666666667